# Generated by Django 5.2.17 on 2026-10-03 15:14

from django.db import migrations, models


def fill_passed(apps, schema_editor):
    Progress = apps.get_model('game', 'Progress')
    for p in Progress.objects.all():
        if p.unlocked_stage > 1 and not p.passed_units:
            p.passed_units = ','.join(str(i) for i in range(1, p.unlocked_stage))
            p.save(update_fields=['passed_units'])


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='passed_units',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(fill_passed, migrations.RunPython.noop),
    ]
